#ifndef __DEFINITIONS__
#define __DEFINITIONS__

//Sizes

#define MAX_SOCKET_BUFF_SIZE 1024u
#define MAX_STR_LEN 64u

//WIFI

#define WIFI_TIMEOUT 8u

#define WIFI_CONFIG_REQUEST_HEADER '1'
#define SUCCESS_RESPONSE_RESULT '0'
#define WIFI_CONFIG_SUCCESS_RESPONSE_HEADER '1'
#define INVALID_WIFI_CONFIG_RESPONSE_HEADER '1'
#define WIFI_CONNECTION_FAILED_RESPONSE_HEADER '2'

#define WIFI_CONFIG_SSID_KEY ("ssid")
#define WIFI_CONFIG_PWD_KEY ("pwd")

#endif
