# This is a basic workflow to help you get started with Actions

name: Well-Sensor ESP32 - Deploy to S3

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [combined-sensor]

env:
  build_name: ${{ format('well-sensor-{0}', github.run_id) }} 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0

      - name: Setup Python
        uses: actions/setup-python@v1.2.0

      - name: Setup Well Sensor Environment
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@1.0.0
          arduino-cli core update-index
          arduino-cli lib install ArduinoJson@6.11.5 PubSubClient@2.7.0 DallasTemperature@3.8.0 OneWire@2.3.4
          arduino-cli core update-index
          pip install pyserial

      - name: Compile Binary
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32 --output ${{ env.build_name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: ${{ env.build_name }}
          # Directory containing files to upload
          path: ${{ format('{0}.bin', env.build_name) }}
          
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    name: Push ESP32 Binary to S3
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: ${{ env.build_name }}
      
      - name: Copy to S3 Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region eu-west-1 \
            ${{ env.build_name }} s3://well-sensor-esp32-bin
       
        
