# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ combined-sensor ]
  pull_request:
    branches: [ combined-sensor ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0

    # Runs a set of commands using the runners shell
    - name: Setup Aduino Environment
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32@1.0.0
        arduino-cli core update-index
        arduino-cli lib install ArduinoJson@6.11.5 PubSubClient@2.7.0 DallasTemperature@3.8.0 OneWire@2.3.4
        arduino-cli core update-index
        
    - name: Compile Binary
      run: |
        apt install python-serial
        arduino-cli compile --fqbn esp32:esp32:esp32
